* added space and speed option keywords to lxt systasks         * added lxt2 support         * updated to latest lxt library code         * lxt 'space' option now uses bzip2 compression         * automatically build man page when help2man is available         * added --disable-lxt configure switch         * cleaned up build process a bit         * checking in bootstrapped files so CVS image can be built           without automake/autoconf tools         * bumped revision to 2.8.5

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,5 +1,5 @@
 AC_PREREQ(2.59)
-AC_INIT(veriwell,2.8.4)
+AC_INIT(veriwell,2.8.5)
 AC_CONFIG_AUX_DIR(config)
 AC_CONFIG_HEADER([config.h])
 
@@ -18,6 +18,12 @@ AC_ARG_ENABLE([lxt],AC_HELP_STRING([--disable-lxt],
 	      [ac_cv_enable_lxt=no],ac_cv_enable_lxt=yes)
 AC_MSG_RESULT([$ac_cv_enable_lxt])
 
+AC_MSG_CHECKING([enable lxt2 support])
+AC_ARG_ENABLE([lxt2],AC_HELP_STRING([--disable-lxt2],
+		                   [compile lxt2 pli routines (default is yes)]),
+	      [ac_cv_enable_lxt2=no],ac_cv_enable_lxt2=yes)
+AC_MSG_RESULT([$ac_cv_enable_lxt2])
+
 # Before configuring libtool check for --enable-all-static option
 AC_ARG_ENABLE(all-static,
   AC_HELP_STRING([--enable-all-static],
@@ -33,6 +39,17 @@ AC_PROG_CXX
 AC_PROG_CC
 AC_PROG_INSTALL
 AC_PROG_RANLIB
+AC_PATH_PROG([HELP2MAN],[help2man])
+AM_CONDITIONAL( [USE_HELP2MAN], [test -n "$HELP2MAN"])
+if test -z "$HELP2MAN"
+then
+        echo ""
+        echo "*** Warning: No suitable help2man found. ***"
+        echo "    The help2man package is essential for rebuilding veriwell "
+        echo "    man pages. You can get away without it when simply "
+	echo "    building from snapshots or major releases."
+        echo ""
+fi
 
 if test X"$ac_cv_enable_m32" = Xyes 
 then  
@@ -99,10 +116,20 @@ fi
 # Checks for libraries.
 AC_CHECK_LIB([z], [gzwrite], [AC_DEFINE(HAVE_LIBZ,[],
 	[Define to 1 if you have the `z' library (-lz).])])
+AC_CHECK_LIB([bz2], [BZ2_bzwrite], [AC_DEFINE(HAVE_LIBBZ2,[],
+	[Define to 1 if you have the `bz2' library (-lbz2).])])
+
 if test X"$ac_cv_enable_lxt" = Xyes; then
     if test X"$ac_cv_lib_z_gzwrite" = Xno; then
         echo ""
         echo "*** Error: libz not found. lxt waveform dumping"
+        echo "    cannot be built. Rerun configure with --disable-lxt."
+        echo ""
+        exit 1;
+    fi
+    if test X"$ac_cv_lib_z_BZ2_bzwrite" = Xno; then
+        echo ""
+        echo "*** Error: libbz2 not found. lxt waveform dumping"
         echo "    cannot be built. Rerun configure with --disable-lxt."
         echo ""
         exit 1;
@@ -141,6 +168,11 @@ AM_CONDITIONAL( [USE_LXT], [test "$ac_cv_enable_lxt" = yes])
 if test "$ac_cv_enable_lxt" = yes 
 then
     AC_DEFINE([HAVE_LXT],1,[Set to one if lxt library should be used])
+fi
+AM_CONDITIONAL( [USE_LXT2], [test "$ac_cv_enable_lxt2" = yes])
+if test "$ac_cv_enable_lxt2" = yes 
+then
+    AC_DEFINE([HAVE_LXT2],1,[Set to one if lxt2 library should be used])
 fi
 
 AC_CONFIG_FILES([Makefile] [replace/Makefile] [src/Makefile] [lxt/Makefile] [doc/Makefile])
