fixed build issues on ppc osx platforms when bz2 and z libs aren't present

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20219,6 +20219,15 @@ if test X"$ac_cv_enable_lxt" = Xyes; then
         exit 1;
     fi
 fi
+if test X"$ac_cv_enable_lxt2" = Xyes; then
+    if test X"$ac_cv_lib_z_gzwrite" = Xno; then
+        echo ""
+        echo "*** Error: libz not found. lxt2 waveform dumping"
+        echo "    cannot be built. Rerun configure with --disable-lxt2."
+        echo ""
+        exit 1;
+    fi
+fi
 
 
   echo "$as_me:$LINENO: checking for a readline compatible library" >&5
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -135,6 +135,15 @@ if test X"$ac_cv_enable_lxt" = Xyes; then
         exit 1;
     fi
 fi
+if test X"$ac_cv_enable_lxt2" = Xyes; then
+    if test X"$ac_cv_lib_z_gzwrite" = Xno; then
+        echo ""
+        echo "*** Error: libz not found. lxt2 waveform dumping"
+        echo "    cannot be built. Rerun configure with --disable-lxt2."
+        echo ""
+        exit 1;
+    fi
+fi
 
 VL_LIB_READLINE
 if test ! "$HAVE_LIBREADLINE" = 1; then
