updating regenerated files

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -462,7 +462,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB HELP2MAN USE_HELP2MAN_TRUE USE_HELP2MAN_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL XGPERF YACC LIBOBJS USE_LXT_TRUE USE_LXT_FALSE USE_LXT2_TRUE USE_LXT2_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB HELP2MAN USE_HELP2MAN_TRUE USE_HELP2MAN_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL XGPERF YACC BUILD_LIBZ_TRUE BUILD_LIBZ_FALSE BUILD_LIBBZ2_TRUE BUILD_LIBBZ2_FALSE LIBOBJS USE_LXT_TRUE USE_LXT_FALSE USE_LXT2_TRUE USE_LXT2_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20002,7 +20002,6 @@ then
         echo ""
 fi
 
-#AC_PROG_YACC
 for ac_prog in bison
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -20130,6 +20129,16 @@ _ACEOF
 
 fi
 
+
+
+if test "$ac_cv_lib_z_gzwrite" = no; then
+  BUILD_LIBZ_TRUE=
+  BUILD_LIBZ_FALSE='#'
+else
+  BUILD_LIBZ_TRUE='#'
+  BUILD_LIBZ_FALSE=
+fi
+
 echo "$as_me:$LINENO: checking for BZ2_bzwrite in -lbz2" >&5
 echo $ECHO_N "checking for BZ2_bzwrite in -lbz2... $ECHO_C" >&6
 if test "${ac_cv_lib_bz2_BZ2_bzwrite+set}" = set; then
@@ -20203,31 +20212,16 @@ _ACEOF
 fi
 
 
-if test X"$ac_cv_enable_lxt" = Xyes; then
-    if test X"$ac_cv_lib_z_gzwrite" = Xno; then
-        echo ""
-        echo "*** Error: libz not found. lxt waveform dumping"
-        echo "    cannot be built. Rerun configure with --disable-lxt."
-        echo ""
-        exit 1;
-    fi
-    if test X"$ac_cv_lib_z_BZ2_bzwrite" = Xno; then
-        echo ""
-        echo "*** Error: libbz2 not found. lxt waveform dumping"
-        echo "    cannot be built. Rerun configure with --disable-lxt."
-        echo ""
-        exit 1;
-    fi
+
+if test "$ac_cv_lib_bz2_BZ2_bzwrite" = no; then
+  BUILD_LIBBZ2_TRUE=
+  BUILD_LIBBZ2_FALSE='#'
+else
+  BUILD_LIBBZ2_TRUE='#'
+  BUILD_LIBBZ2_FALSE=
 fi
-if test X"$ac_cv_enable_lxt2" = Xyes; then
-    if test X"$ac_cv_lib_z_gzwrite" = Xno; then
-        echo ""
-        echo "*** Error: libz not found. lxt2 waveform dumping"
-        echo "    cannot be built. Rerun configure with --disable-lxt2."
-        echo ""
-        exit 1;
-    fi
-fi
+
+
 
 
   echo "$as_me:$LINENO: checking for a readline compatible library" >&5
@@ -22618,7 +22612,7 @@ _ACEOF
 
 fi
 
-                                                  ac_config_files="$ac_config_files Makefile replace/Makefile src/Makefile lxt/Makefile doc/Makefile"
+                                                                      ac_config_files="$ac_config_files Makefile replace/Makefile replace/libz/Makefile replace/libbz2/Makefile src/Makefile lxt/Makefile doc/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -22736,6 +22730,20 @@ if test -z "${USE_HELP2MAN_TRUE}" && test -z "${USE_HELP2MAN_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USE_HELP2MAN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"USE_HELP2MAN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_LIBZ_TRUE}" && test -z "${BUILD_LIBZ_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_LIBZ\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_LIBZ\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_LIBBZ2_TRUE}" && test -z "${BUILD_LIBBZ2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_LIBBZ2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_LIBBZ2\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -23199,6 +23207,8 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "replace/Makefile" ) CONFIG_FILES="$CONFIG_FILES replace/Makefile" ;;
+  "replace/libz/Makefile" ) CONFIG_FILES="$CONFIG_FILES replace/libz/Makefile" ;;
+  "replace/libbz2/Makefile" ) CONFIG_FILES="$CONFIG_FILES replace/libbz2/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "lxt/Makefile" ) CONFIG_FILES="$CONFIG_FILES lxt/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
@@ -23359,6 +23369,10 @@ s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@XGPERF@,$XGPERF,;t t
 s,@YACC@,$YACC,;t t
+s,@BUILD_LIBZ_TRUE@,$BUILD_LIBZ_TRUE,;t t
+s,@BUILD_LIBZ_FALSE@,$BUILD_LIBZ_FALSE,;t t
+s,@BUILD_LIBBZ2_TRUE@,$BUILD_LIBBZ2_TRUE,;t t
+s,@BUILD_LIBBZ2_FALSE@,$BUILD_LIBBZ2_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@USE_LXT_TRUE@,$USE_LXT_TRUE,;t t
 s,@USE_LXT_FALSE@,$USE_LXT_FALSE,;t t
